### ISSUE TITLE
Error when updating sample

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/moneypenny#29]
When updating one sample, money errrs like this:

```
$ moneypenny update lims --sample ADM993A2
lims | samples  [####################################]  100%
lims | cases  [####################################]  100%
lims | customers  [####################################]  100%[2016-06-24 23:20:44,161] moneypenny.update.actions.lims ERROR    error saving customer: cust004
Traceback (most recent call last):
  File "/mnt/hds/proj/bioinfo/components/moneypenny/src/moneypenny/moneypenny/update/actions/lims.py", line 125, in persist
    db.add_commit(customer)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/alchy/manager.py", line 74, in add_commit
    self.add(*instances).commit()
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 767, in _emit_insert_statements
    execute(statement, multiparams)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: customer.id [SQL: u'INSERT INTO customer (id) VALUES (?)'] [parameters: ('cust004',)]
```

**Comment by robinandeer** [comment]
Does this happen consistently? I haven't seen it before

**Comment by ingkebil** [comment]
This only happens when you already updated the database and then update for one sample.

**Comment by robinandeer** [comment]
aha.. yeah I can see that - should be fixed

**Comment by ingkebil** [comment]
Sweet :)
