### ISSUE TITLE
moneypenny update all fails on mongo timeout error

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/moneypenny#32]
```
genotype | success  [####################################]  100%             
Traceback (most recent call last):
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/bin/moneypenny", line 9, in <module>
    load_entry_point('moneypenny', 'console_scripts', 'moneypenny')()
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/mnt/hds/proj/bioinfo/components/moneypenny/src/moneypenny/moneypenny/update/cli/base.py", line 33, in all
    context.invoke(scout)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/mnt/hds/proj/bioinfo/components/moneypenny/src/moneypenny/moneypenny/update/cli/scout.py", line 21, in scout
    process_scout(db, mongo_adapter)
  File "/mnt/hds/proj/bioinfo/components/moneypenny/src/moneypenny/moneypenny/update/actions/scout.py", line 20, in process
    cases = scout_db.cases()
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/scout/ext/backend/case_handler.py", line 95, in cases
    case_query = Case.objects
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/mongoengine/document.py", line 177, in _get_collection
    db = cls._get_db()
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/mongoengine/document.py", line 170, in _get_db
    return get_db(cls._meta.get("db_alias", DEFAULT_CONNECTION_NAME))
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/mongoengine/connection.py", line 152, in get_db
    source=conn_settings['authentication_source'])
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/pymongo/database.py", line 1023, in authenticate
    connect=True)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/pymongo/mongo_client.py", line 419, in _cache_credentials
    writable_preferred_server_selector)
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/pymongo/topology.py", line 142, in select_server
    address))
  File "/mnt/hds/proj/bioinfo/components/maintainance/miniconda/envs/moneypenny/lib/python2.7/site-packages/pymongo/topology.py", line 118, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27023: [Errno 111] Connection refused
```

**Comment by robinandeer** [comment]
Aha! You are running this on rasta, no? I usually open an SSH port but I guess it's closed every times IT updates clincial-db

We should maybe ask them to open a port more permanently like we have for mysql!

**Comment by ingkebil** [comment]
aha! Makes sense :) filing a ticket.
